cmd,internal/govulncheck: fix errors
Fix errors reported by staticcheck and unparam:

cmd/govulncheck/errors.go:20:25: error strings should not be capitalized (ST1005)
cmd/govulncheck/errors.go:20:25: error strings should not end with punctuation or newlines (ST1005)
cmd/govulncheck/errors.go:25:15: error strings should not end with punctuation or newlines (ST1005)
cmd/govulncheck/errors.go:73:6: func inGoPathMode is unused (U1000)
internal/govulncheck/callstacks.go:24:11: unnecessary assignment to the blank identifier (S1005)

client/client.go:518:31: (*client).unionEntries - ctx is unused

Change-Id: I8e6591f9371e3a22ce42d0b4e5dede9cb422fc94
Reviewed-on: https://go-review.googlesource.com/c/vuln/+/473816
Reviewed-by: Julie Qiu <julieqiu@google.com>
Reviewed-by: Zvonimir Pavlinovic <zpavlinovic@google.com>
Run-TryBot: Julie Qiu <julieqiu@google.com>
TryBot-Result: Gopher Robot <gobot@golang.org>